spring.profiles: dev
hspro:
  profile: dev
  comment: devconfig

---
spring.profiles: test
hspro:
  profile: test
  comment: testconfig

---
spring.profiles: prod
hspro:
  profile: prod
  comment: prodconfig
